// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/vector_data.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 671682733932155020),
    name: 'VectorData',
    lastPropertyId: const obx_int.IdUid(5, 5081327009810732125),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8269537387448398019),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 251448427105994828),
        name: 'label',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 3897210356655952382),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5057472529133629055),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 514936022148721144),
        hnswParams: obx_int.ModelHnswParams(dimensions: 512),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8744878996755556188),
        name: 'metadata',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5081327009810732125),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 671682733932155020),
    lastIndexId: const obx_int.IdUid(2, 514936022148721144),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    VectorData: obx_int.EntityDefinition<VectorData>(
      model: _entities[0],
      toOneRelations: (VectorData object) => [],
      toManyRelations: (VectorData object) => {},
      getId: (VectorData object) => object.id,
      setId: (VectorData object, int id) {
        object.id = id;
      },
      objectToFB: (VectorData object, fb.Builder fbb) {
        final labelOffset = fbb.writeString(object.label);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final metadataOffset = object.metadata == null
            ? null
            : fbb.writeString(object.metadata!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, labelOffset);
        fbb.addOffset(2, embeddingOffset);
        fbb.addOffset(3, metadataOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final metadataParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = VectorData(
          label: labelParam,
          embedding: embeddingParam,
          metadata: metadataParam,
          createdAt: createdAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [VectorData] entity fields to define ObjectBox queries.
class VectorData_ {
  /// See [VectorData.id].
  static final id = obx.QueryIntegerProperty<VectorData>(
    _entities[0].properties[0],
  );

  /// See [VectorData.label].
  static final label = obx.QueryStringProperty<VectorData>(
    _entities[0].properties[1],
  );

  /// See [VectorData.embedding].
  static final embedding = obx.QueryHnswProperty<VectorData>(
    _entities[0].properties[2],
  );

  /// See [VectorData.metadata].
  static final metadata = obx.QueryStringProperty<VectorData>(
    _entities[0].properties[3],
  );

  /// See [VectorData.createdAt].
  static final createdAt = obx.QueryDateProperty<VectorData>(
    _entities[0].properties[4],
  );
}
