
PORT = 8888

GEMINI_APIKEY = ""
GEMINI_MODEL = "gemini-2.0-flash" 
# GEMINI_MODEL="gemini-2.5-flash"

REPLY_ON_TAG_BOT_USERNAME=True

DISCORD_PUBKEY = ""
DISCORD_APPID = ""
DISCORD_TOKEN = ""

TELEGRAM_BOT_CHATID="" 

TELEGRAM_BOT_USERNAME = "@dunp_assitant_bot" 
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_API_URL = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"

TELEGRAM_API_ID=""
TELEGRAM_API_HASH=""